[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", VITE_API_URL = "https://visor2030-f642d89e81f4.herokuapp.com/" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200