/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/agregacio': RouteRecordInfo<'/agregacio', '/agregacio', Record<never, never>, Record<never, never>>,
    '/agregacio/': RouteRecordInfo<'/agregacio/', '/agregacio', Record<never, never>, Record<never, never>>,
    '/agregacio/sdg/indicator': RouteRecordInfo<'/agregacio/sdg/indicator', '/agregacio/sdg/indicator', Record<never, never>, Record<never, never>>,
    '/analisi': RouteRecordInfo<'/analisi', '/analisi', Record<never, never>, Record<never, never>>,
    '/avis-legal': RouteRecordInfo<'/avis-legal', '/avis-legal', Record<never, never>, Record<never, never>>,
    '/comarca': RouteRecordInfo<'/comarca', '/comarca', Record<never, never>, Record<never, never>>,
    '/comarca/': RouteRecordInfo<'/comarca/', '/comarca', Record<never, never>, Record<never, never>>,
    '/comarca/sdg/indicator': RouteRecordInfo<'/comarca/sdg/indicator', '/comarca/sdg/indicator', Record<never, never>, Record<never, never>>,
    '/debug': RouteRecordInfo<'/debug', '/debug', Record<never, never>, Record<never, never>>,
    '/metodologia': RouteRecordInfo<'/metodologia', '/metodologia', Record<never, never>, Record<never, never>>,
    '/municipi': RouteRecordInfo<'/municipi', '/municipi', Record<never, never>, Record<never, never>>,
    '/municipi/': RouteRecordInfo<'/municipi/', '/municipi', Record<never, never>, Record<never, never>>,
    '/municipi/programs': RouteRecordInfo<'/municipi/programs', '/municipi/programs', Record<never, never>, Record<never, never>>,
    '/municipi/sdg/budget': RouteRecordInfo<'/municipi/sdg/budget', '/municipi/sdg/budget', Record<never, never>, Record<never, never>>,
    '/municipi/sdg/indicator': RouteRecordInfo<'/municipi/sdg/indicator', '/municipi/sdg/indicator', Record<never, never>, Record<never, never>>,
    '/municipi/sdg/plans': RouteRecordInfo<'/municipi/sdg/plans', '/municipi/sdg/plans', Record<never, never>, Record<never, never>>,
    '/municipi/sdg/valoration': RouteRecordInfo<'/municipi/sdg/valoration', '/municipi/sdg/valoration', Record<never, never>, Record<never, never>>,
    '/ods': RouteRecordInfo<'/ods', '/ods', Record<never, never>, Record<never, never>>,
    '/template': RouteRecordInfo<'/template', '/template', Record<never, never>, Record<never, never>>,
  }
}
